# vim: ai sw=4 expandtab:
import logging
import re
import time
from client.games.zvm import ZorkMachine, ZorkPhone

logger = logging.getLogger(__name__)

INSTANCE_WORDS = [
        # "A",
        # "ACROSS",
        # # "ACTIVATE",
        # # "ADVENTURE",
        # # "ADVERTISE",
        "AGAIN",
        # "AIR",
        "ALL",
        # "ALTAR",
        "AN",
        # "ANCIENT",
        "AND",
        # "ANSWER",
        # "ANTIQUE",
        "APPLY",
        "AROUND",
        # "ART",
        # "ASK",
        "AT",
        # "ATTACH",
        "ATTACK",
        # "AVIATOR",
        # "AWAKE",
        "AWAY",
        # "AX",
        "AXE",
        "BACK",
        "BAG",
        # "BANISH",
        "BAR",
        # "BARE",
        # "BARF",
        # "BARROW",
        "BASKET",
        "BAT",
        # "BATHE",
        "BAUBLE",
        # "BEAUTIFUL",
        # "BEETLE",
        # "BEGONE",
        "BEHIND",
        "BELL",
        "BELOW",
        "BENEATH",
        "BIRD",
        "BIRDSEED",
        # "BITE",
        "BLACK",
        "BLADE",
        # "BLAST",
        # "BLESSING",
        "BLOCK",
        "BLOODY",
        "BLOW",
        # "BLUE",
        "BOARD",
        "BOARDED",
        "BOARDS",
        # "BOAT",
        # "BODIES",
        # "BODY",
        "BOLT",
        # "BONES",
        "BOOK",
        "BOOKLET",
        "BOOKS",
        "BOTTLE",
        "BOX",
        # "BRACELET",
        "BRANCH",
        # "BRANDING",
        # "BRASS",
        "BREAK",
        # "BREATH",
        # "BRIEF",
        "BROKEN",
        "BROWN",
        "BRUSH",
        # "BUBBLE",
        # "BUG",
        # "BUOY",
        # "BURN",
        # "BURNED",
        # "BURNING",
        "BUT",
        # "BUTTON",
        "CAGE",
        "CANARY",
        "CANDLE",
        "CANVAS",
        "CARPET",
        # "CARRY",
        # "CARVED",
        "CASE",
        "CASKET",
        # "CAST",
        # "CATCH",
        # "CHAIN",
        # "CHALICE",
        # "CHANT",
        # "CHASE",
        # "CHASM",
        # "CHEST",
        # "CHESTS",
        "CHIMNEY",
        # "CHOMP",
        # "CHUCK",
        "CHUTE",
        "CLEAN",
        "CLEAR",
        "CLIFF",
        # "CLIFFS",
        "CLIMB",
        # "CLOCKWISE",
        "CLOSE",
        # "CLOVE",
        # "COAL",
        # "COFFIN",
        # "COIL",
        "COINS",
        # "COLONIAL",
        "COME",
        # "COMMAND",
        "CONSUME",
        # "CONTAIN",
        # "CONTROL",
        # "COUNT",
        "COVER",
        "CRACK",
        "CRAWLWAY",
        # "CRETIN",
        # "CROSS",
        # "CRYSTAL",
        "CUP",
        # "CURSE",
        "CUT",
        # "CYCLOPS",
        # "DAM",
        "DAMAGE",
        "DAMN",
        "DARK",
        "DEAD",
        # "DEFLATE",
        # "DERANGED",
        "DESCRIBE",
        "DESTROY",
        # "DIAGNOAL",
        # "DIAMOND",
        "DIG",
        "DINNER",
        "DIRT",
        # "DISEMBOWEL",
        # "DISENCHANT",
        "DISPATCH",
        # "DIVE",
        # "DOME",
        # "DONATE",
        "DOOR",
        # "DOUSE",
        "DOWN",
        "DRINK",
        # "DRIP",
        # "DRIVE",
        # "DRIVER",
        "DROP",
        # "DRYER",
        "DUMBWAITER",
        # "DUSTY",
        "EAST",
        "EAT",
        # "ECHO",
        "EGG",
        # "EGYPTIAN",
        # "ELONGATED",
        "ELVISH",
        # "EMERALD",
        # "ENAMEL",
        # "ENCHANTED",
        "ENCRUSTED",
        # "ENGRAVE",
        # "ENORMOUS",
        "ENTER",
        # "EVIL",
        "EXAMINE",
        # "EXCEPT",
        "EXIT",
        # "EXORCISE",
        # "EXQUISITE",
        # "EXTING",
        # "EYE",
        "FALL",
        # "FANTASY",
        # "FASTEN",
        # # "FCD#",
        # "FEAR",
        # "FEEBLE",
        "FEED",
        "FEEL",
        # "FENCED",
        # "FERMENT",
        # "FIENDS",
        "FIERCE",
        "FIGHT",
        # "FIGURINE",
        # "FILCH",
        "FILL",
        "FIND",
        "FINE",
        # # "FINEPR",
        # # "FIREPR",
        "FIX",
        # "FLAMING",
        # "FLATHEAD",
        # "FLIP",
        # "FLOAT",
        "FLOOR",
        # "FLUORESCENT",
        "FOLLOW",
        # "FOOBAR",
        "FOOD",
        # "FOOTPAD",
        "FOR",
        # "FORBID",
        "FORCE",
        "FORD",
        "FOREST",
        "FORK",
        "FREE",
        # "FREEZE",
        # "FRIGID",
        # "FROBOZ",
        "FROM",
        "FRONT",
        # "FROTZ",
        # "FRY",
        # "FUCK",
        # "FUDGE",
        # "FUMBLE",
        "GARLIC",
        "GAS",
        "GATE",
        # "GATES",
        # "GAZE",
        "GET",
        # "GHOSTS",
        # "GIANT",
        "GIVE",
        # "GLAMDRING",
        "GLASS",
        "GLUE",
        "GO",
        "GOLD",
        # "GOLDEN",
        # "GOTHIC",
        "GRAB",
        # "GRACES",
        # "GRANITE",
        "GRATE",
        # "GRATING",
        # "GREASE",
        # "GREEN",
        "GROUND",
        # "GROUP",
        "GRUE",
        # "GUIDE",
        # "GUIDEBOOK",
        # "GUNK",
        # # "H2O",
        "HAND",
        "HANDS",
        # "HATCH",
        # "HEAD",
        "HEAP",
        "HELLO",
        # "HEMLOCK",
        # "HEMP",
        # "HER",
        "HERE",
        "HI",
        "HIDE",
        # "HIM",
        "HIT",
        "HOLD",
        # "HOP",
        # "HOT",
        "HOUSE",
        "HUGE",
        # "HUNGRY",
        "HURL",
        "HURT",
        # "IGNITE",
        # "IMBIBE",
        # "IMPASS",
        "IN",
        # "INCANTATION",
        # # "INCINE",
        # "INFLATE",
        "INJURE",
        # "INSCRIBE",
        "INSERT",
        "INSIDE",
        # # "INTNUM",
        "INTO",
        "INVENTORY",
        # "INVISIBLE",
        "IS",
        "IT",
        # "IVORY",
        # "JADE",
        "JEWEL",
        # "JEWELED",
        # "JEWELS",
        "JUMP",
        "KEY",
        "KICK",
        "KILL",
        "KISS",
        "KITCHEN",
        "KNIFE",
        # "KNIVES",
        # "KNOCK",
        # "LABEL",
        "LADDER",
        # "LAKE",
        "LAMP",
        # "LAND",
        "LANTERN",
        # "LARGE",
        # "LAUNCH",
        "LEAF",
        "LEAFLET",
        # "LEAK",
        # "LEAN",
        # "LEAP",
        # "LEATHER",
        "LEAVE",
        "LEAVES",
        # "LEDGE",
        "LETTER",
        # "LID",
        "LIFT",
        "LIGHT",
        "LIQUID",
        # "LIQUIFY",
        "LISTEN",
        "LOCK",
        # "LONG",
        "LOOK",
        # "LOSE",
        # "LOWER",
        # "LOWERED",
        # "LUBRICATE",
        "LUNCH",
        # "LUNGS",
        # "LURKING",
        # "MACHINE",
        # "MAGIC",
        "MAIL",
        "MAILBOX",
        "MAKE",
        "MAN",
        # "MANGLED",
        # "MANUAL",
        "MAP",
        # "MARBLE",
        # "MASSIVE",
        "MATCH",
        "MATCHBOOK",
        # "MATCHED",
        # "MATERIAL",
        "ME",
        # "MELT",
        # "METAL",
        "MIRROR",
        # "MOLEST",
        # "MONSTER",
        # "MOUNTAIN",
        "MOUTH",
        "MOVE",
        # "MUMBLE",
        # "MURDER",
        "MYSELF",
        "NAIL",
        # "NAILS",
        # "NARROW",
        # "NASTY",
        "NEST",
        "NO",
        "NORTH",
        "NORTHEAST",
        "NORTHWEST",
        # "NUT",
        # "ODOR",
        # "ODYSSEY",
        "OF",
        "OFF",
        # "OFFER",
        # "OIL",
        "OLD",
        "ON",
        "ONE",
        # "ONTO",
        "OPEN",
        # "ORCRIST",
        # "ORIENT",
        "OUT",
        "OVER",
        # "OVERBOARD",
        # "OWN",
        # "OWNERS",
        # "OZMOO",
        # "PAGE",
        # "PAINT",
        # "PAINTING",
        # "PAIR",
        # "PANEL",
        "PAPER",
        # "PARCHMENT",
        "PASSAGE",
        # "PASTE",
        # "PAT",
        # "PATCH",
        "PATH",
        # # "PDP1",
        # "PEAL",
        # "PEDESTAL",
        "PEPPER",
        "PERSON",
        "PET",
        "PICK",
        # "PIECE",
        # "PIERCE",
        # "PILE",
        "PINES",
        "PIPE",
        "PLACE",
        # "PLASTIC",
        # "PLATING",
        "PLAY",
        "PLUG",
        # "PLUGH",
        # "POKE",
        # "POSEIDEN",
        "POT",
        "POUR",
        # "PRAY",
        # "PRAYER",
        "PRESS",
        # "PRINT",
        # "PROCEED",
        "PULL",
        # "PUMP",
        # "PUNCTURE",
        # "PURSUE",
        "PUSH",
        "PUT",
        # "QUANTITY",
        "QUIT",
        # "RAFT",
        # "RAIL",
        # "RAILING",
        # "RAINBOW",
        "RAISE",
        "RAMP",
        # "RANGE",
        # "RAP",
        # "RAPE",
        "READ",
        # "RED",
        # "REFLECT",
        # "RELEASE",
        # "REMAIN",
        "REMOVE",
        # "REPAIR",
        # "REPENT",
        # "REPLY",
        "RESTART",
        "RESTORE",
        # "RICKETY",
        "RING",
        "RIVER",
        # "ROBBER",
        # "ROCKY",
        # "ROLL",
        "ROPE",
        "RUB",
        "RUG",
        "RUN",
        # "RUSTY",
        "SACK",
        # "SAILOR",
        # "SAND",
        "SANDWICH",
        # "SAPPHIRE",
        "SAVE",
        "SAY",
        # "SCARAB",
        # "SCEPTER",
        # "SCEPTRE",
        "SCORE",
        "SCREAM",
        # "SCREW",
        # "SCREWDRIVER",
        # "SCRIPT",
        "SEARCH",
        # "SEAWORTHY",
        # "SECURE",
        "SEE",
        # "SEEDY",
        # "SEEK",
        # "SELF",
        "SEND",
        "SET",
        # "SHADY",
        # "SHAKE",
        # "SHARP",
        # "SHEER",
        # "SHIT",
        # "SHOUT",
        # "SHOVEL",
        "SHUT",
        # "SIGH",
        # "SILENT",
        # "SILVER",
        # "SINISTER",
        "SIT",
        # "SKELETON",
        # "SKIM",
        # "SKIP",
        # "SKULL",
        # "SLAG",
        "SLAY",
        "SLICE",
        "SLIDE",
        "SMALL",
        # "SMASH",
        "SMELL",
        # "SMELLY",
        "SNIFF",
        # "SOLID",
        # "SONG",
        # "SONGBIRD",
        "SOUTH",
        "SOUTHEAST",
        "SOUTHWEST",
        "SPILL",
        "SPIN",
        # "SPIRIT",
        # "SPRAY",
        # "SQUEEZE",
        "STAB",
        "STAIRCASE",
        "STAIRS",
        "STAIRWAY",
        # "STAND",
        # "STARE",
        # "STARTLE",
        "STAY",
        # "STEEP",
        # "STEP",
        # "STEPS",
        # "STILETO",
        "STONE",
        # "STORM",
        # "STRANGE",
        "STREAM",
        "STRIKE",
        "STUFF",
        # "SUPER",
        "SUPERBRIEF",
        # "SURPRISE",
        # "SURROUND",
        # "SUSPICIOUS",
        "SWALLOW",
        "SWIM",
        "SWING",
        "SWITCH",
        "SWORD",
        "TABLE",
        "TAKE",
        "TALK",
        # "TAN",
        "TASTE",
        "TAUNT",
        "TEETH",
        "TELL",
        # "TEMPLE",
        "THE",
        "THEM",
        "THEN",
        "THIEF",
        # "THIEFS",
        # "THROUGH",
        "THROW",
        "THRU",
        # "THRUST",
        "TIE",
        # "TIMBER",
        "TO",
        # "TOMB",
        # "TOOL",
        # "TOOLCHEST",
        # "TOOLS",
        # "TOOTH",
        "TORCH",
        "TOSS",
        "TOUCH",
        # "TOUR",
        "TRAIL",
        "TRAP",
        "TRAPDOOR",
        # "TREASURE",
        "TREE",
        "TREES",
        # "TRIDENT",
        # "TROLL",
        # "TROPHY",
        # "TRUNK",
        # "TUBE",
        # "TUG",
        # "TURN",
        # "TWISTING",
        # "ULYSSEYS",
        # "UNATTACHED",
        "UNDER",
        "UNDERNEATH",
        # "UNFASTEN",
        # "UNHOOK",
        "UNLOCK",
        # "UNRUST",
        # "UNSCRIPTED",
        "UNTIE",
        "UP",
        # "USELESS",
        # "USING",
        # "VALVE",
        # "VAMPIRE",
        "VERBOSE",
        "VERSION",
        # "VICIOUS",
        # "VISCOUS",
        # "VITREOLIC",
        "WADE",
        "WAIT",
        "WAKE",
        "WALK",
        "WALL",
        # "WALLS",
        "WATER",
        "WAVE",
        "WEAR",
        "WEST",
        "WHAT",
        "WHATS",
        "WHERE",
        # "WHITE",
        # "WIN",
        # "WIND",
        # "WINDING",
        "WINDOW",
        # "WINNAGE",
        # "WISH",
        "WITH",
        "WOODEN",
        # "WRENCH",
        # "WRITING",
        "XYZZY",
        # "YANK",
        "YELL",
        # "YELLOW",
        "YES",
        "ZORK",
        # "ZORKMID",
        # "ZZMGCK",
]

WORDS = [ 'PLAY', 'ZORK' ]
# WORDS = ZORK_WORDS

PRIORITY = 100

def textmunge(text):
    replacements = [(r'Copyright \(c\) 1981, 1982, 1983 Infocom, Inc\. All rights reserved\.', 'Copyright 1981, 1982, 1983 Infocom'),
                    (r'Revision \d+ / Serial number \d+\r\n', '')]
    for pattern, replacement in replacements:
        text = re.sub(pattern, replacement, text, re.MULTILINE)
    return text

def quit_heard(phone, zork_said):
    logger.debug('quit_heard handler running')
    nuke_text = ' (Y is affirmative): >'
    ind = zork_said.find(nuke_text)
    if ind >= 0:
        zork_said = zork_said[:ind] + zork_said[ind + len(nuke_text):]
        phone.context['state'] = 'waiting_for_quit_confirmation'
    return zork_said
   
def quit_handler(text, match, phone):
    logger.debug('Heard quit')
    phone.talker_handler = quit_heard

def save_handler(text, match, phone):
    logger.debug('Heard save')
    phone.talker_handler = save_heard

def restore_handler(text, match, phone):
    logger.debug('Heard restore')
    phone.talker_handler = restore_heard

def save_heard(phone, zork_said):
    logger.debug('save_heard handler running')
    if 'Enter a file name' in zork_said:
        phone.announce('Saving')
        phone.zvm.write('\n')
        time.sleep(0.1)
        zork_said = phone.zvm.read()
        if 'Y/N' in zork_said:
            phone.zvm.write('y\n')
            zork_said = 'Overwrote old save'
    return zork_said

def restore_heard(phone, zork_said):
    logger.debug('restore_heard handler running')
    if 'Enter a file name' in zork_said:
        phone.announce('Loading')
        phone.zvm.write('\n')
        time.sleep(0.1)
        zork_said = phone.zvm.read()
    return zork_said

def default_listen_handler(text, match, phone):
    logger.debug('Default listen handler')
    if 'state' in phone.context and phone.context['state'] == 'waiting_for_quit_confirmation':
        return quit_confirm(text, match, phone)

def quit_confirm(text, match, phone):
    logger.debug('Waiting for quit confirmation')
    phone.context['state'] = None
    if text.upper() == 'YES':
        phone.running = False
        phone.zvm.write(text+'\n');
        phone.mic.say('That was a good game');
        raise phone.StopGame()

listen_handlers = [
    (re.compile(r'quit', re.IGNORECASE), quit_handler),
    (re.compile(r'save', re.IGNORECASE), save_handler),
    (re.compile(r'restore', re.IGNORECASE), restore_handler),
    (re.compile(r'.'), default_listen_handler),  # The default handler NEEDS to be last.
]

def handle(text, mic, profile):
    """
    Play a game of zork
    """

    mic.say('Lets play a game of zork')

    zvm = ZorkMachine()
    zorkphone = ZorkPhone(zvm, mic,
                          munger=textmunge,
                          listen_handlers=listen_handlers)
    zorkphone.talker.join()
    zorkphone.listener.join()

    mic.say('Thank you for making an old grue very happy.')

def isValid(text):
    """
    "Play Zork"
    """

    # return bool(re.search(r'\bplay zork\b', text, re.IGNORECASE))
    return bool(re.search(r'\bzork\b', text, re.IGNORECASE))
